### ISSUE TITLE
Separate Luncher and Main

### ISSUE THREAD

**Issue by tdurieux** [castor-software/pankti#10]
I saw https://github.com/castor-software/pankti/blob/master/src/main/java/launchers/PanktiLauncher.java which is the main class of the project. It is designed to be called with the command line.
I would recommend to rename that class to  'PanktiMain' and create `PanktiLauncher`, the difference between the two is that the second one is meant to be called using the Java API. It will be useful for testing your software.

`PanktiMain` would only define the command line parameter and call `PanktiLauncher`.

**Comment by tdurieux** [comment]
Also, create a class that will contain all the results of your analysis. For the moment, it is not possible to extract the data when you are cooling Pankti, it makes it hard to test.

**Comment by Deee92** [comment]
Thanks @tdurieux. To actually see the paths of candidate methods, you can uncomment the lines in `applyProcessor(CtModel)` in `PanktiLauncher`, while I work on a more elegant solution!
