### ISSUE TITLE
generate a csv for the methods which are covered by workload

### ISSUE THREAD

**Issue by gluckzhang** [castor-software/pankti#18]
Currently it is fine to directly use `instrumentation-candidates.csv` as one of the inputs for pankti-generate, but for uncovered methods a `java.io.FileNotFoundException` will be raised.

What about generating a new csv file after running pankti-generate, to only include the covered rows in `instrumentation-candidates.csv`? Extra metrics could be added as well, such as the number of unique pairs/triples of object values, and the number of generated test cases.

This csv file can be used for a comparision with jacoco's report, in order to find out which method is untested in the original test suite, but has pankti-generated test cases.

@Deee92 , what do you think?

**Comment by Deee92** [comment]
@gluckzhang, a CSV for invoked methods is definitely a TODO! Thanks.

**Comment by Deee92** [comment]
@gluckzhang, a CSV for invoked methods is now generated along with object serialization, as of 797f6f020ea7aa8a877d8e57f79ef327abc4445f. However, its columns are similar to the CSV for instrumented methods.

**Comment by gluckzhang** [comment]
This feature works well and I am closing the issue. Thanks @Deee92 !
